### PR TITLE
Allow explicit server key using MOSH_OVERRIDE_KEY_FROM_FILE

### PR DESCRIPTION
**Pull request by vi**
For setting up emergency UDP-only shell access with a static pre-configured key.

Inspired by [mosh-mallet](https://gitlab.com/Zinnia_Zirconium/mosh-mallet).

Note: prototype-grade code quality; if the feature is desired I can create a better version of a pull request.

### CODE REVIEW

**Comment by achernya** [comment]
This feature makes me incredibly nervous. Having a mosh-server process listening with a key and no client connecting to it means that there's an initial state with no nonce and therefore no AEAD operable. Any client that happens to guess the 128-bit key (which is not super likely, that's not an easy brute force) could take over the session. This is partly why mosh-server exits if it doesn't hear back from a client within 60s on startup.

**Comment by andersk** [comment]
Mosh requires a fresh random key for each session. Modifying Mosh to reuse a key will [compromise its cryptographic security](https://web.cs.ucdavis.edu/~rogaway/ocb/ocb-faq.htm#nonce). (This isn’t about guessing the key by brute force—it’s about cleverly correlating packets from different sessions encrypted using the same key.)

**Comment by vi** [comment]
Looks like some better DTLS- or QUIC-based UDP negotiator is needed.

**Comment by vi** [comment]
Created my own alternative to mosh-mallet: https://github.com/vi/moshudp, supposedly without proper security.

**Pull request closed without merging**
