### PR TITLE
Clang formatting traces

### PR DESCRIPTION
**Pull request by carloscabanero**
When applying the new formatting from our side, I noticed these three files (one line each), had been left over.

### CODE REVIEW

**Comment by achernya** [comment]
It looks like this PR fails our clang-format CI check. Which version of clang-format are you using?

**Comment by carloscabanero** [comment]
Yep, on those exact 3 lines. I'm running `clang-format version 18.1.3`. Just saw the pipelines are using version 14. Is there any reason for that? I gotta say the one liners with (x) looked better in the new. No worries then, feel free to close.

**Comment by achernya** [comment]
14 was the version that we did the initial clang-format with. We can upgrade, but haven't gotten around to it yet.

**Comment by carloscabanero** [comment]
I can try to help with that if you want me to. I'm on it and looks like it will only pull 3 simple changes in the repository.

**Pull request closed without merging**
