### PR TITLE
Fix emoji render issue on MSYS2

### PR DESCRIPTION
**Pull request by lifei**
This pr can make mosh rendering emoji on MSYS2 work fine.

### CODE REVIEW

**Comment by achernya** [comment]
I don't understand the underlying reasoning of this PR. I am primarily concerned that it seems to sometimes return a wcwidth of 2, but I'm not convinced that those scenarios are correct. Can you provide some comments/documentation/reasoning for this change?

I believe a more correct fix is for mosh to ship its own up-to-date wcwidth tables, but I'm open to this PR if we can understand its effects more thoroughly.

I'd like to see tests added before this can be merged as well.

**Comment by lifei** [comment]
> I don't understand the underlying reasoning of this PR. I am primarily concerned that it seems to sometimes return a wcwidth of 2, but I'm not convinced that those scenarios are correct. Can you provide some comments/documentation/reasoning for this change?
> 
> I believe a more correct fix is for mosh to ship its own up-to-date wcwidth tables, but I'm open to this PR if we can understand its effects more thoroughly.
> 
> I'd like to see tests added before this can be merged as well.

`wcwidth` is not the main problem. the root cause is `mbrtowc` takes 3 `char`s return 1 `wchar_t`s and the right result should be taking 4 `char`s return 2 `wchar_t`s in windows/msys2. also the wcrtomb has the same issue. so i use mbstowcs instead of mbtowc functions.

I update pr and add some comments.

**Comment by keithw** [comment]
For historical note: Mosh requires (or at least checks and warns) if the system doesn't set __STDC_ISO_10646__, meaning, wchar_t represents a Unicode Scalar Value, end of story.

It looks like you're talking about a non-STDC_ISO_10646 system where wchar_t represents something else (a UTF-16 code unit). This is outside the bounds of what Mosh has tried to support in the past (hence the check and warning at build time), but of course it's totally reasonable if people want to take on this support burden.

I would worry that it does make the parser more complicated to branch on this at runtime -- maybe there should be an entirely different parser for wchar_t=UTF-16 architectures that gets linked in at compile time? But that's just spitballing.

**Comment by lifei** [comment]
> parser

the parser is almost unchanged, for the improvement just appear on the condition with the failure of the pwccheck. so it should be just some small corner case fix for the parser.

a big change in this pr i think should be adding a field `raw` to class Print. And i suggest that in common case the filed `raw` is also reasonable, for chars has been converted twice through the process. it convert to wcahr_t when saving to the Print, and convert back to char when print to the console.

**Comment by achernya** [comment]
@lifei the screenshot you posted honestly leaves me with more concerns. Given what @keithw said above, it seems that this is "WAI" from a mosh perspective that `wchat_t` is a UTF-8 type, and making this work on Windows is a lot more involved than this PR accomplishes. I am not comfortable merging this PR as a result.

**Comment by achernya** [comment]
You cannot "just cut the UTF-8 chars into Cells correctly" without a lot more information. The bug here, as Keith mentioned above, is an incompatibility between the parser's state machine and the type of `wchar_t`. As we've seen here some characters take multiple cells, hence the calls to `wcwidth`. You can't do this with "No unicode, no `wchar_t`".

**Pull request closed without merging**
