### PR TITLE
Issues/431/dev: configuration file implementation

### PR DESCRIPTION
**Pull request by earlchew**

### CODE REVIEW

**Comment by cgull** [comment]
I'm a little uncomfortable with adding an ad-hoc config file parser in a security-sensitive program, and I'm not sure SSH is a good example to follow, perhaps YAML might be better here.

I echo @andersk in saying surely there must be a simpler way, though I don't know what it is either.

**Comment by glensc** [comment]
testing `ConfigFile` package inside main mosh script? does not seem like super idea.

maybe use existing CPAN module to parse the config, and if want to avoid depending on CPAN modules in distribution (why?), could use some other module that inlines needed CPAN modules during build process. Can't give any reference which tool it is, as haven't used any myself, but there exists, maybe even several projects.

**Comment by ekacnet** [comment]
FYI my PR. is similar to this but:
I'm only adding ~130 lines, most of commits are cosmetics and are meant for reducing the risk of forgetting options (ie. by not having them spread all across the script).

It's really handy to have the capacity to set some options like predict or the path to the server command, it's also handy if you have to use a custom ssh command as I do when I do port knocking or use 2FA like yubikeys

**Comment by achernya** [comment]
Thanks for this change. However, I think it takes an approach that is different from how we've decided we want to go in #431, and currently has a lot of conflicts for merging, so closing in its current form.

**Pull request closed without merging**
