### PR TITLE
updated bash completion

### PR DESCRIPTION
**Pull request by sbdchd**
I modified the bash completion file so that flags are partially completed.

### CODE REVIEW

**Comment by cgull** [comment]
We want this, I think, but I'm no bash-completion expert.
* What OSes and versions have you tested this on?
* What versions of bash-completion and Bash will this work with?

**Comment by sbdchd** [comment]
I have tested this with bash_completion 2.1 & bash version 4.3 on Ubuntu and OS X.

I am fairly certain that this requires at least bash_completion 2, since it uses `_init_completion`.

**Comment by cgull** [comment]
The thing that's keeping me from taking this is that OS X has bash 3.2 as its default shell, which these changes will break on.  But at least with our packages and Homebrew, bash-completion is not configured by default, and so I don't *think* that's actually a problem.  I don't know anything about MacPorts or enough about bash-completion usage on OS X to decide-- anyone have any wisdom in this area?

**Comment by sbdchd** [comment]
The existing implementation of bash-completion for mosh requires at least bash-completion 2, which itself requires Bash 4.

So the current setup doesn't work on OS X without installing bash-completion 2 and upgrading the default Bash installation to Bash 4.

**Comment by cgull** [comment]
I just merged a combination of your PR and @y-higuchi's bash-completion compatibility code.  Would you please verify that this works as you expect?

**Comment by sbdchd** [comment]
Working great!
Thanks.

**Comment by cgull** [comment]
Pulled.

**Pull request closed without merging**
