### PR TITLE
Style/perfomance/good practice

### PR DESCRIPTION
**Pull request by RussianBruteForce**
Just some improvements.

### CODE REVIEW

**Comment by cgull** [comment]
Thanks! These  look like good changes, but I'd ask for a few things:

* English is full of irregular verbs, please change "sended" to "sent".
* Please make your code easy to review now, and study in the future: Rebase it to eliminate intermediate/incomplete/revised changes, such as your series of changes in `calculate_timers()` (probably some of these should still be separate, but changes such as your "Fix compilation" commit, or revision of the same work, should be squashed).  Also, your changes should be on a single branch from master without merges from or to master (Mosh takes contributions by rebasing, not merging).
* Review your changes to `calculate_timers()` to make sure you haven't changed the logic (it is unfortunately rather complex).
* Did you find these issues with an analysis tool? If so, please consider adding a Makefile target for the tool.  I actually have some for a few tools but I never merged them.

These would go in after 1.2.6 is released, so there's no reason to hurry.

**Comment by glensc** [comment]
@cgull i think he did not realize his master is linked to this PR. a common mistake when people make PR from master branch. so you can merge locally, just do `git reset --hard` to remove the merge commits top of the branch.

**Comment by glensc** [comment]
@RussianBruteForce you can fix this PR by removing last commits with:

```
git checkout master
git reset --hard ef9467f31330b6abfdc7e29d2bf7b19abcb0a334
git push -f
```

and add commits @cgull has asked.

and do not update your `master` branch with other changes than related to this PR until this PR is merged, as any push is linked to this PR.

**Comment by cgull** [comment]
1.2.6 is done and I'm still interested in these.  I realized later that the tool you used must have been `cppcheck` or something related, but it found different things than my `cppcheck` run.  Or maybe you found some extra things by doing code review.  What tool did you use?  How did you choose which findings/alerts to use?

**Comment by RussianBruteForce** [comment]
Hi @cgull, sorry for my sloth.
I use my eyes and search tool 'ag' (aka the_silver_searcher) and of course I run 'cppcheck'. I'll correct mistakes in several days or so. Thank you all for feedback.

**Comment by eminence** [comment]
@RussianBruteForce requested that this be closed in https://github.com/mobile-shell/mosh/pull/800#issue-173846115

**Pull request closed without merging**
