### PR TITLE
Release CI using Github Actions

### PR DESCRIPTION
**Pull request by achernya**

### CODE REVIEW

**Review by bbarenblat — APPROVED** [review]

**Comment by eminence** [comment]
This is a pretty minor thing (and might not be worth changing now), but I wouldn't mind seeing the ubuntu and macos stuff as separate jobs.  Of the 12 build steps, only 4 of them are common to both platforms.  As the cost of a small amount of duplication, it might make the whole thing easier to read.

**Comment by eminence** [comment]
Any thoughts about how to do #1008 with github actions?

**Comment by achernya** [comment]
I'm not sure if we can. We'd have to provide github actions with a PGP key to sign the releases. I'll have to do some research to see if we can securely store a PGP key in a way accessible to Github's standard runners. Otherwise we'll have to provide a custom runner, which I am not thrilled about doing, as we'd need to get a VM somewhere.

**Comment by eminence** [comment]
Github's [secret management](https://docs.github.com/en/actions/security-guides/encrypted-secrets) is pretty well regarded, as far as I know.    But maybe we won't want to trust that.

Actually, it is probably easier if we don't do this with CI.  Maybe github CI creates the [pre]release, one of the core maintainers downloads the tarball, signs it, manually uploads the signature, and then clicks the button on the github website to convert the pre-release into a release.

**Comment by achernya** [comment]
That's certainly the easiest way, but then we have to figure out where to store this PGP key :), restoring it to the same problem. Let me look into secret management.

**Pull request merged**
