### PR TITLE
Prevent defunct mosh-server processes from piling up

### PR DESCRIPTION
**Pull request by palmer-dabbelt**
I've recently started using Mosh, and it seems really useful.  I was wondering what happens when my most-client dies, and according to some GitHub issues it appears that mosh-server just keeps running indefinately.  This seems bad to me, so I went ahead and added a check to mosh-server that causes the server to terminate after it's seen no clients for a long time.  The default timeout is one week.

Note that I'm new to both using Mosh and the source, so this might be the wrong way to do it.  Specifically:
* Should I be throwing some sort of exception?  Directly doing an exit(5) seems like a bad idea...
* Should the timeout exist in some configuration file?  I can't find a config file for Mosh so I now just have a compile-time constant.
* Is this even necessary?  I haven't tested it with the full week timeout, but I did test it with a 30 second timeout and this patch causes mosh-server to terminate when it would usually stick around.

### CODE REVIEW

**Comment by jaseg** [comment]
Another way to solve this would be to present the mosh wrapper with an unique, per-client id. The mosh wrapper would then kill any existing server processes using the same id before spawning a new server.

In most cases, zombie servers are probably created when you reboot your client, and in these cases the newly spawned mosh wrapper could just kill any lingering mosh servers using the same id. This still allows multiple mosh instances per server.

A hackish way to auto-generate that unique ID could be to use a tuple of $(hostname) and $USER (thereby not allowing multiple parallell mosh sessions between two hosts without manually chaning this id).

**Comment by colindean** [comment]
I was just looking for a solution to this problem. It'd be great if this made it into a release.

**Comment by cgull** [comment]
See also #12

**Comment by cgull** [comment]
I've merged #690 which is a more complete solution.  Let me know if this works for you.

**Comment by palmer-dabbelt** [comment]
That works for me.  Thanks!

**Pull request closed without merging**
