### PR TITLE
Add support for dynamic IP hosts

### PR DESCRIPTION
**Pull request by nogy**
Until now every time the hosts IP changed, the mosh-server would
keep running with the mosh-client unable to reconnect.
now Ctrl+^ r will re-lookup the dns entry and adjust the address
information accordingly. That way the connection can be revived.

### CODE REVIEW

**Comment by normanr** [comment]
Instead of adding a new host arg, why not just support passing hostname or ip as the first arg?

**Comment by normanr** [comment]
Actually it looks like this goes some way towards fixing #210 and #212 :-)

**Comment by andersk** [comment]
@normanr: The extra argument is important to make sure we use the same IP to which we connected over SSH. If we were to re-resolve the same hostname immediately, which might get a different address family that we can’t connect over, or a different host behind a round-robin DNS load balancer.

The same concerns apply to this patch as written, but at least this will only happen if the user invokes the functionality manually. If they do, though, they might not have a good way to recover. What we really want the client to do is to try both the old and new IP addresses until it starts getting responses from the new one.

**Comment by nogy** [comment]
@andersk You are right with the load balancer. The way of trying both old and new IP addresses would indeed resolve this. I was a bit afraid about the multiple resolve attempts clogging up the possibly slow connection at the times where a slow connection keeps you from getting responses from the old IP in the first place. So deciding when to start the re-lookup process automagically is what keeps me from finishing this. Manually I have a good guess on when my server changed its IP.

**Comment by timofonic** [comment]
@keithw @nogy @normanr @andersk Any news about this? It's open since 2015. Why?

**Comment by jkoop** [comment]
Hey just curious why this hasn't been merged, yet. Is there a UI problem? Is it compilation? Documentation? DNS round-robin?

DNS round-robin can be delt with by just mentioning (in the manual) that this feature may not work well with such domain names, since it sounds like it's totally up to the user anyway.

I'd *love* this to be merged, since my server is behind DDNS.

**Comment by nogy** [comment]
Hi,

I ported this again recently. I've had a discussion with Keith about how to trigger another resolution attempt several years ago. I haven't had the time to implement the change though. (And frankly disagreed to have the resolution trigger automatically after a certain timeout). The patch gives you the option of re-resolving by a meta-keycombination. Auto-resolving would clog an already slow connection. I guess by modern standards there is no 'slow' connections anywhere but maybe in Germany *sic*. So I would add that now. On the other hand there is also a shell script wrapper that should allow you to re-connect to a mosh session iirc.

Cheers Bastian

Am 19. April 2022 23:38:24 MESZ schrieb Joe Koop ***@***.***>:

**Comment by achernya** [comment]
We're going to solve this more generally with the plans in #212 and #1214. Since this has merge conflicts, closing in its current form.

**Pull request closed without merging**
