### PR TITLE
Adds Dockerfile-s for building a static mosh-server on Alpine Linux

### PR DESCRIPTION
**Pull request by javabrett**
Prototype dockerfiles to build/test a statically-linked (musl glibc) mosh-server.  Part of research on #188.
- Dockerfile - Alpine linux base, installed build toolchain, checks-out mosh master, builds/installs, starts sshd and creates a mosh test-user.
- Dockerfile.ubuntu - Ubuntu base running sshd with mosh test-user.

### CODE REVIEW

**Comment by eminence** [comment]
I just tested this out.  The build seemed to be fine, but when I tried to copy the static `mosh-server` binary to my gentoo machine, it segfaults when I run it.  Does this happen for you?

**Comment by javabrett** [comment]
@eminence I had not tested the static `mosh-server` with Gentoo, only Ubuntu.  So I just created a Gentoo test-target dockerfile and added that.  From my testing on this image, the same static `mosh-server` worked ok, so no segfault.

Can you repeat the test using `Dockerfile.gentoo` as the host for the static `mosh-server` and report whether it works for you?  Should do, and if-so would need more details on the target Gentoo host that you tested on, details of the segfault etc.

**Comment by eminence** [comment]
I tested the musl-static `mosh-server` in the image created by `Dockerfile.gentoo` and it still segfaults.  

Here's what gdb has to say (running on my gentoo host, not a gentoo docker guest):

```
Program received signal SIGSEGV, Segmentation fault.
memcpy () at src/string/x86_64/memcpy.s:18
18      src/string/x86_64/memcpy.s: No such file or directory.
(gdb) bt
#0  memcpy () at src/string/x86_64/memcpy.s:18
#1  0x000055555565065c in __copy_tls (mem=0x5555558d0438 <builtin_tls+56> "") at src/env/__init_tls.c:60
#2  0x00005555556507a2 in static_init_tls (aux=aux@entry=0x7fffffffdc00) at src/env/__init_tls.c:127
#3  0x0000555555644877 in __init_libc (envp=envp@entry=0x7fffffffdda0, pn=<optimized out>) at src/env/__libc_start_main.c:38
#4  0x0000555555644991 in __libc_start_main (main=0x55555557c2a0 <main(int, char**)>, argc=2, argv=0x7fffffffdd88) at src/env/__libc_start_main.c:70
#5  0x000055555558017f in __dls2 (base=<optimized out>, sp=<optimized out>) at crt/rcrt1.c:14
#6  0x000055555558000d in _start ()
```

**Comment by javabrett** [comment]
@eminence thanks for testing and the stack-trace.

Unfortunately I've not been able to reproduce this yet.  Similar crashes in bugtrackers (mainly for Alpine) for musl glibc seem to indicate that it could relate to a much smaller default stack size in musl.

Not sure what to suggest next.  Is it easy to compile a `mosh-server` static within a Gentoo image?  I'm not as familiar with Gentoo images or dev tool-chain.  Maybe a statically-linked version built on Gentoo will run there.  I did hope that the binary would be fairly portable though.

**Comment by javabrett** [comment]
I'm going to close this PR - other discussions e.g. https://github.com/mobile-shell/moshweb/pull/47 lead me to believe that it is better to pursue dynamically-linked options with relocated/local dependencies as a non-root install-option, that the difficulty of a (portable?) statically-linked build.

Thanks for the testing anyway.

**Pull request closed without merging**
