### PR TITLE
Fix build on Haiku.

### PR DESCRIPTION
**Pull request by diversys**

### CODE REVIEW

**Comment by cgull** [comment]
This looks good, but could I ask for a few things here?

* What version of Haiku is this patch for?  What functionality does it get/not get?
* Please convert the header conditional into an autoconf test.
* Similarly, is there any way we can make the other change less OS-specific?  Maybe we can make this a run-time check with `I_LOOK` or `I_FIND`.
* If you can, please run `make check` with `tmux` installed; this will help validate that Mosh works properly on Haiku.

**Comment by diversys** [comment]
This is against the latest nightly: https://download.haiku-os.org/nightly-images/x86_gcc2_hybrid/
You can run an ISO in VirtualBox or VMware.

There is a recipe available for the latest version of mosh: https://github.com/haikuports/haikuports/blob/master/net-misc/mosh/mosh-1.3.0.recipe

For some reason it's much slower than ssh. The lag is very noticeable - typing anything causes 1 sec delay before text appears, so something doesn't work right yet. Would be cool if you could look into it.
For this you will need to install Haiku from ISO (literally 1 minute)

1. `pkgman install haikuporter` 
2. edit `/system/settings/haikuports.conf`
3. add a few lines to bash profile https://github.com/haikuports/haikuports/wiki#tips
4. `hp mosh` will build a package from the recipe I linked above

All in all should take about 5 minutes to setup this environment.

Me or @pulkomandy will try to address your comments as time permits.
Interestingly, most of the tests fail with the same message: `no usable locale`

<details>
  <summary>Click to expand make check</summary>
PASS: ocb-aes
PASS: encrypt-decrypt
PASS: base64
PASS: nonce-incr
ERROR: local.test
ERROR: e2e-success.test
ERROR: e2e-failure.test
ERROR: emulation-ascii-iso-8859.test
ERROR: emulation-80th-column.test
ERROR: emulation-attributes-vt100.test
ERROR: emulation-attributes-16color.test
ERROR: emulation-attributes-256color8.test
ERROR: emulation-attributes-256color248.test
ERROR: emulation-back-tab.test
ERROR: emulation-cursor-motion.test
ERROR: emulation-multiline-scroll.test
ERROR: emulation-wrap-across-frames.test
ERROR: network-no-diff.test
ERROR: prediction-unicode.test
ERROR: pty-deadlock.test
ERROR: repeat.test
ERROR: repeat-with-input.test
ERROR: server-network-timeout.test
ERROR: server-signal-timeout.test
ERROR: window-resize.test
ERROR: unicode-combine-fallback-assert.test
ERROR: unicode-later-combining.test
============================================================================
Testsuite summary for mosh 1.3.0
============================================================================
# TOTAL: 28
# PASS:  4
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 24
============================================================================
See src/tests/test-suite.log
Please report to mosh-devel@mit.edu
============================================================================
Makefile:852: recipe for target 'test-suite.log' failed
make[5]: *** [test-suite.log] Error 1
make[5]: Leaving directory '/sources/mosh-1.3.0/src/tests'
Makefile:958: recipe for target 'check-TESTS' failed
make[4]: *** [check-TESTS] Error 2
make[4]: Leaving directory '/sources/mosh-1.3.0/src/tests'
Makefile:1052: recipe for target 'check-am' failed
make[3]: *** [check-am] Error 2
make[3]: Leaving directory '/sources/mosh-1.3.0/src/tests'
Makefile:344: recipe for target 'check-recursive' failed
make[2]: *** [check-recursive] Error 1
make[2]: Leaving directory '/sources/mosh-1.3.0/src'
Makefile:392: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/sources/mosh-1.3.0'
Makefile:681: recipe for target 'check' failed
make: *** [check] Error 2
</details>

<details>
  <summary>Click to expand test-suite.log</summary>
  ==========================================
   mosh 1.3.0: src/tests/test-suite.log
==========================================

# TOTAL: 28
# PASS:  4
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 24

.. contents:: :depth: 2

ERROR: local
============

./local.test: no usable locale
ERROR local.test (exit status: 99)

ERROR: e2e-success
==================

e2e-test: no usable locale
ERROR e2e-success.test (exit status: 99)

ERROR: e2e-failure
==================

e2e-test: no usable locale
ERROR e2e-failure.test (exit status: 99)

ERROR: emulation-ascii-iso-8859
===============================

e2e-test: no usable locale
ERROR emulation-ascii-iso-8859.test (exit status: 99)

ERROR: emulation-80th-column
============================

e2e-test: no usable locale
ERROR emulation-80th-column.test (exit status: 99)

ERROR: emulation-attributes-vt100
=================================

e2e-test: no usable locale
ERROR emulation-attributes-vt100.test (exit status: 99)

ERROR: emulation-attributes-16color
===================================

e2e-test: no usable locale
ERROR emulation-attributes-16color.test (exit status: 99)

ERROR: emulation-attributes-256color8
=====================================

e2e-test: no usable locale
ERROR emulation-attributes-256color8.test (exit status: 99)

ERROR: emulation-attributes-256color248
=======================================

e2e-test: no usable locale
ERROR emulation-attributes-256color248.test (exit status: 99)

ERROR: emulation-back-tab
=========================

e2e-test: no usable locale
ERROR emulation-back-tab.test (exit status: 99)

ERROR: emulation-cursor-motion
==============================

e2e-test: no usable locale
ERROR emulation-cursor-motion.test (exit status: 99)

ERROR: emulation-multiline-scroll
=================================

e2e-test: no usable locale
ERROR emulation-multiline-scroll.test (exit status: 99)

ERROR: emulation-wrap-across-frames
===================================

e2e-test: no usable locale
ERROR emulation-wrap-across-frames.test (exit status: 99)

ERROR: network-no-diff
======================

e2e-test: no usable locale
ERROR network-no-diff.test (exit status: 99)

ERROR: prediction-unicode
=========================

e2e-test: no usable locale
ERROR prediction-unicode.test (exit status: 99)

ERROR: pty-deadlock
===================

e2e-test: no usable locale
ERROR pty-deadlock.test (exit status: 99)

ERROR: repeat
=============

e2e-test: no usable locale
ERROR repeat.test (exit status: 99)

ERROR: repeat-with-input
========================

e2e-test: no usable locale
ERROR repeat-with-input.test (exit status: 99)

ERROR: server-network-timeout
=============================

e2e-test: no usable locale
ERROR server-network-timeout.test (exit status: 99)

ERROR: server-signal-timeout
============================

e2e-test: no usable locale
ERROR server-signal-timeout.test (exit status: 99)

ERROR: window-resize
====================

e2e-test: no usable locale
ERROR window-resize.test (exit status: 99)

ERROR: unicode-combine-fallback-assert
======================================

e2e-test: no usable locale
ERROR unicode-combine-fallback-assert.test (exit status: 99)

ERROR: unicode-later-combining
==============================

e2e-test: no usable locale
ERROR unicode-later-combining.test (exit status: 99)

ERROR: window-resize
====================

e2e-test: no usable locale
ERROR window-resize.test (exit status: 99)
</details>

**Comment by cgull** [comment]
Mosh needs a UTF-8 locale.  Do `export LANG=en_US.UTF-8` or whatever the equivalent is on Haiku, with whatever language you prefer, before you run `make check`.  The test in `src/tests/e2e-test-subr` does have problems, you might have to disable it to get it running on Haiku.

As for working on Haiku myself:  Sorry, no.  I gave it a good half hour, and found I had a `gcc2` system unable to build mosh.  Haiku is quite the niche OS and I think you'll have to resolve the issues yourself, there are more important Mosh issues for me to work on.

I did come up with improvements for the issues I asked about, would you give #874 a try?

**Comment by pulkomandy** [comment]
These changes were not really ready for upstreaming.

I reworked things and made the proper fixes. Haiku does have a forkpty, so we may as well use it.

The problem with the tests is that our "locale" command does not handle the "charmap" argument. I changed to -m which I think is the POSIX standard way to do it (and I also fixed -m to do the right thing in Haiku).

Patchfile available here:
https://raw.githubusercontent.com/haikuports/haikuports/272811a75268efef3f1cb96bedd9cbaf21a41d2e/net-misc/mosh/patches/mosh-1.3.0.patchset

With this, the previous changes are not needed anymore, since we won't use the custom forkpty anymore.

Also, just to stop the rumor that we still use gcc2 for everything: all you need to do is "setarch x86", that sets up a development environment with an up to date gcc5. Or, you can just use the 64bit version of Haiku which is legacy-free and does not include gcc2 at all.

**Comment by cgull** [comment]
The forkpty change looks good, I'll take it.
The `locale -m` change isn't quite right.  On at least macOS and Linux, that reports all available charmaps, not the one currently in use.  You may want to check that you've implemented that feature correctly on Haiku.  As for the Mosh build, I have a fix that avoids `locale` entirely by building a little program to test for UTF-8ness, coming soon.

**Comment by cgull** [comment]
I've pulled #875, so this is now done, I think.

**Pull request closed without merging**
