### PR TITLE
Improve cursor style handling

### LINKED ISSUE #1084: Cursor style not handled correctly
My cursor changes style from pipe to rectangle in ZSH shell when use vim mode but also in vim when switching from Normal and Insert modes. The cursor changes styles when I use ssh but in a mosh session, I see only the pipe-style cursor and it never changes.

Is there a way to fix that behavior?

I'm using the latest git version build on the server and on the client.
Server - archlinux: `mosh 1.3.2 [build mosh-1.3.2-86-g0cc492d]`
Client - macosx: `mosh 1.3.2 [build mosh-1.3.2-86-g0cc492d]`

### PR DESCRIPTION
**Pull request by matheusfillipe**
Fixes #1084

### CODE REVIEW

**Comment by aurelienbottazini** [comment]
Works for me

**Comment by fbernier** [comment]
This fixes the issue for me too.

Arch + alacritty -> arch + alacritty

**Comment by demon386** [comment]
+1

**Comment by jeremybahadirli** [comment]
Any idea whether this is slated to be merged prior to the Mosh 1.4 release?

**Comment by achernya** [comment]
My plan is for 1.4 to be a release of existing merged commits and a future release will include any outstanding PRs

**Comment by martijk** [comment]
It doesn't seem to do anything for me with kitty and the patch applied on both sides on top of mosh-stable.

**Comment by bcp-dev-ops** [comment]
is it possible to merge?

**Comment by MahdiNazemi** [comment]
Would it be possible for someone familiar with the code to update this PR to resolve its merge conflicts with the master branch?
I attempted twice but it looks like some files like `shared.h` no longer exist in the master branch.

**Comment by matheusfillipe** [comment]
#1292

**Comment by martijk** [comment]
> It doesn't seem to do anything for me with kitty or Tilix and the patch applied on both sides on top of mosh-stable. What I did to test:
> 
>     * `printf '\x1b]12;%s\a' '#ffffe4e4c4c4'`
> 
>     * use the [Terminus VIM plugin](https://github.com/wincent/terminus), which changes the cursor shape based on the mode
> 
> 
> The client side is Fedora 37, server side RHEL 8. Command that I used: `/local/path/to/patched/mosh --server=/remote/path/to/patched/mosh-server <server>`.

It does work, or at least with #1292. The issue was that the `bin` directory of the patched mosh wasn't in my path, which probably meant that it was executing `mosh-client` from my system installation.

**Comment by eggbean** [comment]
I find that `/usr/local/bin` is a good location that overrides package installed software.

**Pull request closed without merging**
